# Minimal Mistakes Jekyll Theme Configuration
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "sunrise" # or "air", "aqua", "contrast", "dark", etc.

# Site Settings
locale: "en-US"
title: "Inverse Kinematics Approximation with Machine Learning"
title_separator: "-"
subtitle: "Joao Pedro Dudziak Fonseca, Jackson Merrick, Anand Nagpurkar"
name: ""
description: ""
url: "https://github.gatech.edu/pages/jfonseca32/IK-ML-Project/"
repository: "jfonseca32/IK-ML-Project"
teaser: "https://github.gatech.edu/user-attachments/assets/07a7ac11-be95-481a-8d4c-ebb46390448c"
logo: "https://github.gatech.edu/user-attachments/assets/8ba1a9a1-448e-44eb-b3fa-e7b0ae495f2f"
masthead_title: "Inverse Kinematics Approximation with Machine Learning"
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: false
copyright: ""
copyright_url: ""
  
# Site Author
author:
  name: "Joao Pedro <br> \n Dudziak Fonseca"
  avatar: "https://github.gatech.edu/user-attachments/assets/1afc3591-53b6-4179-b83a-358ef334075c"
  location: "Atlanta, Georgia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.gatech.edu/jfonseca32/IK-ML-Project"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joao-pedro-dudziak-fonseca/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jfonseca32@gatech.edu"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.gatech.edu/jfonseca32/IK-ML-Project"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joao-pedro-dudziak-fonseca/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jfonseca32@gatech.edu"
  since: "July 10th, 2025"
  
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: "America/New_York" # Set your timezone if you want

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression (optional)
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
