# Minimal Mistakes Jekyll Theme Configuration
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "sunrise" # or "air", "aqua", "contrast", "dark", etc.

# Site Settings
locale: "en-US"
title: "Inverse Kinematics Approximation with Machine Learning"
title_separator: "-"
subtitle: "Joao Pedro Dudziak Fonseca, Jackson Merrick, Anand Nagpurkar"
name: ""
description: ""
url: "https://jfonseca32.github.io/Inverse-Kinematics-Approximation-with-ML/"
repository: "https://github.com/jfonseca32/Inverse-Kinematics-Approximation-with-ML/"
teaser: ""
logo: "https://github.com/user-attachments/assets/4e9bbaa7-5277-44b8-8fdd-d0b27cf8bb33"
masthead_title: "Inverse Kinematics Approximation with Machine Learning"
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: false
copyright: ""
copyright_url: ""
  
# Site Author
author:
  name: "Joao Pedro <br> \n Dudziak Fonseca"
  avatar: "https://private-user-images.githubusercontent.com/54600227/475778070-1cd6ab05-1455-4fd3-857e-11b3c5456c09.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ2MDEzMDUsIm5iZiI6MTc1NDYwMTAwNSwicGF0aCI6Ii81NDYwMDIyNy80NzU3NzgwNzAtMWNkNmFiMDUtMTQ1NS00ZmQzLTg1N2UtMTFiM2M1NDU2YzA5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA3VDIxMTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNmE2YTAwODFmM2JhZjY2MGQzYmMxZjUzMmE1NzE3YjVjNDllMGEwZGZiNDk4ZDllMzgzOGIyMWRiMTk2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jbua8dpWbuBbwHmGEm_9tvhCupbLqb_2ykv4JwwrF1U"
  location: "Atlanta, Georgia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jfonseca32/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joao-pedro-dudziak-fonseca/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jfonseca32@gatech.edu"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jfonseca32/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joao-pedro-dudziak-fonseca/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jfonseca32@gatech.edu"
  since: "July 10th, 2025"
  
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: "America/New_York" # Set your timezone if you want

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression (optional)
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
